### ISSUE TITLE
load_facts is not idempotent

### ISSUE THREAD

**Issue by tobyink** [xsawyerx/acme-rafl-everywhere#3]
Hopefully this illustrates what I mean...

```
use 5.010;
use Acme::rafl::Everywhere;
use Test::More;

my $A = Acme::rafl::Everywhere->new;  # rafl is so everywhere
my $B = Acme::rafl::Everywhere->new;  # but he's not here!

for (0..4)
{
    like($A->fact, qr{^rafl is so everywhere});
    like($B->fact, qr{^rafl is so everywhere});
}

done_testing();
```

One simple solution would be to make `Acme::rafl::Everywhere` a singleton, and always return the same object from `new`.

**Comment by xsawyerx** [comment]
The problem seems to be that when the lines are read again, it doesn't rewind the file but rather continues from where it stopped. I wonder if I should raise this issue on #p5p.

Regardless, I don't do singletons. We can simply put the facts as a default value in the object instead of reading it from **DATA**.

**Comment by xsawyerx** [comment]
Fixed in new version and released. Thanks! :)
